# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Angle_Block_Design_2_wrapper.xdc

# Block Designs: bd/Angle_Block_Design_2/Angle_Block_Design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2 || ORIG_REF_NAME==Angle_Block_Design_2}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_processing_system7_0_0/Angle_Block_Design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_processing_system7_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_processing_system7_0_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_0_0/Angle_Block_Design_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_0_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_processing_system7_0_axi_periph_0/Angle_Block_Design_2_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Angle_Block_Design_2_processing_system7_0_axi_periph_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_rst_processing_system7_0_100M_0/Angle_Block_Design_2_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_1_0/Angle_Block_Design_2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_1_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_1_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_xbar_0/Angle_Block_Design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_xbar_0 || ORIG_REF_NAME==Angle_Block_Design_2_xbar_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_xlconcat_0_0/Angle_Block_Design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_xlconcat_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_xlconcat_0_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_2_0/Angle_Block_Design_2_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_2_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_2_0}]

# IP: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_auto_pc_0/Angle_Block_Design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_auto_pc_0 || ORIG_REF_NAME==Angle_Block_Design_2_auto_pc_0}]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_processing_system7_0_0/Angle_Block_Design_2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_processing_system7_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_0_0/Angle_Block_Design_2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_0_0/Angle_Block_Design_2_axi_gpio_0_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_0_0/Angle_Block_Design_2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_0_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_rst_processing_system7_0_100M_0/Angle_Block_Design_2_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0}]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_rst_processing_system7_0_100M_0/Angle_Block_Design_2_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Angle_Block_Design_2_rst_processing_system7_0_100M_0}]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_rst_processing_system7_0_100M_0/Angle_Block_Design_2_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_1_0/Angle_Block_Design_2_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_1_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_1_0/Angle_Block_Design_2_axi_gpio_1_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_1_0/Angle_Block_Design_2_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_1_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_xbar_0/Angle_Block_Design_2_xbar_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_2_0/Angle_Block_Design_2_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_2_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_2_0/Angle_Block_Design_2_axi_gpio_2_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_axi_gpio_2_0/Angle_Block_Design_2_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Angle_Block_Design_2_axi_gpio_2_0 || ORIG_REF_NAME==Angle_Block_Design_2_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/Angle_Block_Design_2/ip/Angle_Block_Design_2_auto_pc_0/Angle_Block_Design_2_auto_pc_0_ooc.xdc

# XDC: bd/Angle_Block_Design_2/Angle_Block_Design_2_ooc.xdc
