webtalk_init -webtalk_dir /home/zynquser/Vivado/Encoder_Hardware/Encoder_Hardware.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 27 12:21:42 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210930187_1777494212_210594536_408" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pu8roaddqbastt5p0b0njf69v0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.6 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292.439 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1461781197000" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1461781197000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1461781197000"
webtalk_transmit -clientid 2433420752 -regid "210930187_1777494212_210594536_408" -xml /home/zynquser/Vivado/Encoder_Hardware/Encoder_Hardware.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/zynquser/Vivado/Encoder_Hardware/Encoder_Hardware.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/zynquser/Vivado/Encoder_Hardware/Encoder_Hardware.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
